##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  spring配置  ###################
server :
  port : 8086
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  ##项目名字配置
  #servlet :
  #  context-path : /demo
  tomcat :
    uri-encoding : UTF-8
    #xx 报错修改的地方
    max-connections: 200000
    max-http-form-post-size: 9000000
    threads:
      max: 128
      min-spare: 5
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT
    username: demo
    password: 123456
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
mybatis:
  #配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations : classpath*:mybatis/*.xml

###################  INDEX配置  ###################